name: GitHub Pages

on:
    push:
        branches:
            - main # Set a branch to deploy
    pull_request:
    schedule:
        - cron: '*/5 * * * *'
        - cron: '59 4 1-28 12 *' # Every day at 4am 59 from December 1st to 28st

jobs:
    deploy:
        runs-on: ubuntu-22.04
        concurrency:
            group: ${{ github.workflow }}-${{ github.ref }}
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: true # Fetch Hugo themes (true OR recursive)
                  fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

            - name: Setup Node.js and Yarn
              uses: actions/setup-node@v3
              with:
                  node-version: 20

            - name: Install dependencies
              run: yarn install

            - name: Setup Hugo
              uses: peaceiris/actions-hugo@v2
              with:
                  hugo-version: '0.117.0'
                  extended: true

            - name: Build
              run: yarn build

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              if: github.ref == 'refs/heads/main'
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./public
